apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"five-containers","namespace":"default"},"spec":{"containers":[{"image":"localhost:5000/dl_iris_dataset:latest","name":"dataset-loader","volumeMounts":[{"mountPath":"/irisdata","name":"shared-data"}]},{"args":["-c","echo Hello from the model container \u003e /pod-data/index.html"],"command":["/bin/sh"],"image":"localhost:5000/keras/alone:latest","name":"model","volumeMounts":[{"mountPath":"/pod-data","name":"shared-data"}]},{"image":"localhost:5000/keras/alone:latest","name":"optimizer","volumeMounts":[{"mountPath":"/output","name":"shared-data"}]},{"args":["-c","echo Hello from the eval container \u003e /pod-data/index.html"],"command":["/bin/sh"],"image":"localhost:5000/keras/alone:latest","name":"eval","volumeMounts":[{"mountPath":"/output","name":"shared-data"}]},{"image":"localhost:5000/keras/alone:latest","name":"prediction","volumeMounts":[{"mountPath":"/prediction","name":"shared-data"}]}],"restartPolicy":"Never","volumes":[{"emptyDir":{},"name":"shared-data"}]}}
  creationTimestamp: "2021-06-03T14:23:44Z"
  name: five-containers
  namespace: default
  resourceVersion: "2564"
  uid: 58fdf2b5-89ac-4191-9ea7-a2d092971607
spec:
  containers:
  - image: localhost:5000/dl_iris_dataset:latest
    imagePullPolicy: Always
    name: dataset-loader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /irisdata
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wtp5s
      readOnly: true
  - args:
    - -c
    - echo Hello from the model container > /pod-data/index.html
    command:
    - /bin/sh
    image: localhost:5000/keras/alone:latest
    imagePullPolicy: Always
    name: model
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /pod-data
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wtp5s
      readOnly: true
  - image: localhost:5000/keras/alone:latest
    imagePullPolicy: Always
    name: optimizer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /output
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wtp5s
      readOnly: true
  - args:
    - -c
    - echo Hello from the eval container > /pod-data/index.html
    command:
    - /bin/sh
    image: localhost:5000/keras/alone:latest
    imagePullPolicy: Always
    name: eval
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /output
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wtp5s
      readOnly: true
  - image: localhost:5000/keras/alone:latest
    imagePullPolicy: Always
    name: prediction
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /prediction
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wtp5s
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: iris-clf2-worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: shared-data
  - name: kube-api-access-wtp5s
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T14:23:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T14:23:44Z"
    message: 'containers with unready status: [dataset-loader model optimizer eval
      prediction]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T14:23:44Z"
    message: 'containers with unready status: [dataset-loader model optimizer eval
      prediction]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T14:23:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://47bba3635f00221d86528abfaa897b7b3fa44e53866c303d3cdfccd04336a33e
    image: localhost:5000/dl_iris_dataset:latest
    imageID: localhost:5000/dl_iris_dataset@sha256:52f8601e48170e23390a4f45dc51b7639dbc43fecec87f58facd4b9a41670c07
    lastState: {}
    name: dataset-loader
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://47bba3635f00221d86528abfaa897b7b3fa44e53866c303d3cdfccd04336a33e
        exitCode: 0
        finishedAt: "2021-06-03T14:23:51Z"
        reason: Completed
        startedAt: "2021-06-03T14:23:51Z"
  - containerID: containerd://69e632858b156e0a852cccde5ecd6564baa0537fa322dd34da09ee1f6a7349bf
    image: localhost:5000/keras/alone:latest
    imageID: localhost:5000/keras/alone@sha256:691e455a39ad148a735b1820522143f0b323ac62530733d181f14ae0abbae446
    lastState: {}
    name: eval
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://69e632858b156e0a852cccde5ecd6564baa0537fa322dd34da09ee1f6a7349bf
        exitCode: 2
        finishedAt: "2021-06-03T14:25:02Z"
        reason: Error
        startedAt: "2021-06-03T14:25:02Z"
  - containerID: containerd://55e40edd03f983b40a02a22e5f539f06e9213c0f096e92f16c08ca6a69294c62
    image: localhost:5000/keras/alone:latest
    imageID: localhost:5000/keras/alone@sha256:691e455a39ad148a735b1820522143f0b323ac62530733d181f14ae0abbae446
    lastState: {}
    name: model
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://55e40edd03f983b40a02a22e5f539f06e9213c0f096e92f16c08ca6a69294c62
        exitCode: 0
        finishedAt: "2021-06-03T14:25:01Z"
        reason: Completed
        startedAt: "2021-06-03T14:25:01Z"
  - containerID: containerd://b0cfe4732e5e997a9abf45d16b81fe77792f5f81bd7d926ea0e459b8cee92fb2
    image: localhost:5000/keras/alone:latest
    imageID: localhost:5000/keras/alone@sha256:691e455a39ad148a735b1820522143f0b323ac62530733d181f14ae0abbae446
    lastState: {}
    name: optimizer
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://b0cfe4732e5e997a9abf45d16b81fe77792f5f81bd7d926ea0e459b8cee92fb2
        exitCode: 0
        finishedAt: "2021-06-03T14:25:01Z"
        reason: Completed
        startedAt: "2021-06-03T14:25:01Z"
  - containerID: containerd://59222385f865cf53ad47974ef9251fd8f6c86516d7d62dcd6edc319551710ba3
    image: localhost:5000/keras/alone:latest
    imageID: localhost:5000/keras/alone@sha256:691e455a39ad148a735b1820522143f0b323ac62530733d181f14ae0abbae446
    lastState: {}
    name: prediction
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://59222385f865cf53ad47974ef9251fd8f6c86516d7d62dcd6edc319551710ba3
        exitCode: 0
        finishedAt: "2021-06-03T14:25:02Z"
        reason: Completed
        startedAt: "2021-06-03T14:25:02Z"
  hostIP: 172.18.0.2
  phase: Failed
  podIP: 10.244.2.2
  podIPs:
  - ip: 10.244.2.2
  qosClass: BestEffort
  startTime: "2021-06-03T14:23:44Z"
