kubectl get pod five-containers --output=yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"five-containers","namespace":"default"},"spec":{"containers":[{"image":"dl_iris_dataset","name":"dataset-loader","volumeMounts":[{"mountPath":"/irisdata","name":"shared-data"}]},{"args":["-c","echo Hello from the model container \u003e /pod-data/index.html"],"command":["/bin/sh"],"image":"keras/alone","name":"model","volumeMounts":[{"mountPath":"/pod-data","name":"shared-data"}]},{"image":"keras/alone","name":"optimizer","volumeMounts":[{"mountPath":"/output","name":"shared-data"}]},{"args":["-c","echo Hello from the eval container \u003e /pod-data/index.html"],"command":["/bin/sh"],"image":"keras/scikit-learn","name":"eval","volumeMounts":[{"mountPath":"/output","name":"shared-data"}]},{"image":"keras/scikit-learn","name":"prediction","volumeMounts":[{"mountPath":"/prediction","name":"shared-data"}]}],"restartPolicy":"Never","volumes":[{"emptyDir":{},"name":"shared-data"}]}}
  creationTimestamp: "2021-06-03T10:31:03Z"
  name: five-containers
  namespace: default
  resourceVersion: "63253"
  uid: ed6cbec7-d109-41f8-a921-14fbf39aa61a
spec:
  containers:
  - image: dl_iris_dataset
    imagePullPolicy: Always
    name: dataset-loader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /irisdata
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8tfkg
      readOnly: true
  - args:
    - -c
    - echo Hello from the model container > /pod-data/index.html
    command:
    - /bin/sh
    image: keras/alone
    imagePullPolicy: Always
    name: model
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /pod-data
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8tfkg
      readOnly: true
  - image: keras/alone
    imagePullPolicy: Always
    name: optimizer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /output
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8tfkg
      readOnly: true
  - args:
    - -c
    - echo Hello from the eval container > /pod-data/index.html
    command:
    - /bin/sh
    image: keras/scikit-learn
    imagePullPolicy: Always
    name: eval
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /output
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8tfkg
      readOnly: true
  - image: keras/scikit-learn
    imagePullPolicy: Always
    name: prediction
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /prediction
      name: shared-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8tfkg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: iris-clf1-worker3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: shared-data
  - name: kube-api-access-8tfkg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T10:31:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T10:31:04Z"
    message: 'containers with unready status: [dataset-loader model optimizer eval
      prediction]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T10:31:04Z"
    message: 'containers with unready status: [dataset-loader model optimizer eval
      prediction]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-06-03T10:31:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: dl_iris_dataset
    imageID: ""
    lastState: {}
    name: dataset-loader
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "dl_iris_dataset"
        reason: ImagePullBackOff
  - image: keras/scikit-learn
    imageID: ""
    lastState: {}
    name: eval
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "keras/scikit-learn"
        reason: ImagePullBackOff
  - image: keras/alone
    imageID: ""
    lastState: {}
    name: model
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "keras/alone"
        reason: ImagePullBackOff
  - image: keras/alone
    imageID: ""
    lastState: {}
    name: optimizer
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "keras/alone"
        reason: ImagePullBackOff
  - image: keras/scikit-learn
    imageID: ""
    lastState: {}
    name: prediction
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "keras/scikit-learn"
        reason: ImagePullBackOff
  hostIP: 172.18.0.4
  phase: Pending
  podIP: 10.244.3.2
  podIPs:
  - ip: 10.244.3.2
  qosClass: BestEffort
  startTime: "2021-06-03T10:31:04Z"
pimpwhippa@pimpwhippa-Aspire-E5-473G:~/Works/ImpactTech/pod$ kubectl get pods
NAME              READY   STATUS             RESTARTS   AGE
five-containers   0/5     ImagePullBackOff   0          8m20s
two-containers    1/2     NotReady           0          116m
pimpwhippa@pimpwhippa-Aspire-E5-473G:~/Works/ImpactTech/pod$ kubectl get pods
