apiVersion: v1
kind: Pod
metadata:
  name: five-containers
spec:

  restartPolicy: Never

  #volumes:
  #- name: shared-data
  #  emptyDir: {}

  containers:

  - name: dataset-loader
    image: localhost:5000/dl_iris_dataset:latest
    volumeMounts:
    - name: iris-clf-shared-data
      mountPath: /irisdata

  - name: model
    image: localhost:5000/keras/alone:latest
    volumeMounts:
    - name: iris-clf-shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the model container > /pod-data/index.html"]

  - name: optimizer
    image: localhost:5000/keras/alone:latest
    volumeMounts:
    - name: iris-clf-shared-data
      mountPath: /output

  - name: eval
    image: localhost:5000/keras/alone:latest
    volumeMounts:
    - name: iris-clf-shared-data
      mountPath: /output
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the eval container > /pod-data/index.html"]

  - name: prediction
    image: localhost:5000/keras/alone:latest
    volumeMounts:
    - name: iris-clf-shared-data
      mountPath: /prediction
      
volumes:
- name: iris-clf-shared-data
  emptyDir: {}